### PR TITLE
I added the credits part, I hope you like it

### PR DESCRIPTION
**Pull request by Matte0000**
I saw that this website did not have the part of the contributors and I thought of adding it, I really hope you like it because we have put in a lot of time (it still lacks some style). :)

### CODE REVIEW

**Comment by paganim** [comment]
I see All checks have failed 1 failing check. What means?

**Comment by SamirJouni** [comment]
It means that the Continuous Integration is failing to build the project. If you click on details, you can see that it says the error is: 
```
Failed to compile.

./src/components/Credits.js

  Line 405:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener  react/jsx-no-target-blank
```

**Comment by paganim** [comment]
So what i have to do?

**Comment by SamirJouni** [comment]
Nevermind, I fixed it, you just had to add rel="noopener noreferrer" after target="_blank". It's a stupid error. Browsers should deal with it implicitly...

**Comment by paganim** [comment]
Thanks very much! :)

**Pull request merged**
