### PR TITLE
Edited the link tag of the footer

### PR DESCRIPTION
**Pull request by w3bh4ck**
Had to target a blank window whenever the user clicks on any of the social icons.

### CODE REVIEW

**Comment by w3bh4ck** [comment]
I will like to be added as a contributor. I believe i can learn a lot from this.

**Comment by w3bh4ck** [comment]
alright

**Comment by w3bh4ck** [comment]
alright

**Comment by pavelisp** [comment]
I hate to do this, but apparently the reason why I see all the errors is because when putting _blank target in react/jsx creates a security issue. Read up on it here and see if you can find a way to write it out in a way that doesn't get flagged as an error :) [JSX NO TARGET](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md)

**Comment by SamirJouni** [comment]
As pavel said... target="_blank" is a security issue, because the site being opened can actually change the already opened site, to say a phishing site, by using the window.opener object.
just add the attribute: rel="noopener noreferrer"
And your issue will be solved.

**Pull request closed without merging**
